# Spring 配置项
server:
    max-http-header-size: 102400

spring:
    output:
        ansi:
            enabled: always
    mvc:
        throw-exception-if-no-handler-found: true
    web:
        resources:
            add-mappings: false
    autoconfigure:
        exclude:
            - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
            - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
            - org.springframework.boot.actuate.autoconfigure.metrics.jdbc.DataSourcePoolMetricsAutoConfiguration
            - org.springframework.boot.actuate.autoconfigure.metrics.KafkaMetricsAutoConfiguration
            - org.springframework.boot.actuate.autoconfigure.metrics.LogbackMetricsAutoConfiguration
            - org.springframework.boot.autoconfigure.data.redis.RedisReactiveAutoConfiguration
            - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
    main:
        lazy-initialization: false
    aop:
        proxy-target-class: true
    jackson:
        default-property-inclusion: non_null

logging:
    config: classpath:logback-spring.xml

management:
    endpoints:
        web:
            base-path: /actuator
            exposure:
                include: health, prometheus, env
    metrics:
        tags:
            application: ${spring.application.name}

vehicle:
    version: 2.1.0-SNAPSHOT
